spring.application.name=fx-catalog-service
server.port=8002
course.service.url=http://localhost:8001
spring.main.allow-bean-definition-overriding=true

# Parte 1: Configuracion para el Agente Java de OpenTelemetry
# El agente lee estas propiedades automaticamente al arrancar con -javaagent
otel.service.name=fx-catalog-service
otel.exporter.otlp.endpoint=http://localhost:4317
otel.exporter.otlp.protocol=grpc
otel.traces.exporter=otlp
otel.metrics.exporter=none
otel.logs.exporter=none